-- LuaDC version 0.9.19
-- 5/23/2004 7:23:49 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
UC_Family("Fighter", 28)
UC_FamilyOverride("Vaygr", "Fighter", 36)
UC_Family("Corvette", 24)
UC_ShipType("MinelayerCorvette", 10)
UC_Family("Frigate", 42)
UC_ShipType("DefenseFieldFrigate", 4)
UC_ShipType("CaptureFrigate", 12)
UC_ShipTypeOverride("Hiigaran", "CaptureFrigate", 8)
UC_Family("Capital", 26)
UC_FamilyOverride("Vaygr", "Capital", 30)
UC_ShipType("Destroyer", 10)
UC_ShipType("Carrier", 8)
UC_ShipTypeOverride("Vaygr", "Carrier", 12)
UC_ShipType("Battlecruiser", 6)
UC_ShipType("Shipyard", 4)
UC_Family("Utility", 100)
UC_ShipType("Dreadnaught", 2)
UC_ShipType("Battlecruiser", 6)
UC_ShipType("ResourceCollector", 40)
UC_ShipType("ResourceController", 8)
UC_ShipType("Probe", 20)
UC_ShipType("ECMProbe", 20)
UC_ShipType("ProximitySensor", 20)
UC_Family("Platform", 40)
UC_ShipType("HyperspacePlatform", 8)
UC_Family("Mothership", 12)
UC_Family("SinglePlayerMisc", 200)