-- LuaDC version 0.9.19
-- 5/23/2004 7:23:49 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
UC_Family("Fighter", 14)
UC_FamilyOverride("Vaygr", "Fighter", 18)
UC_Family("Corvette", 12)
UC_ShipType("MinelayerCorvette", 5)
UC_Family("Frigate", 21)
UC_ShipType("DefenseFieldFrigate", 2)
UC_ShipType("CaptureFrigate", 6)
UC_ShipTypeOverride("Hiigaran", "CaptureFrigate", 4)
UC_Family("Capital", 13)
UC_FamilyOverride("Vaygr", "Capital", 15)
UC_ShipType("Destroyer", 5)
UC_ShipType("Carrier", 4)
UC_ShipTypeOverride("Vaygr", "Carrier", 6)
UC_ShipType("Battlecruiser", 3)
UC_ShipType("Shipyard", 2)
UC_Family("Utility", 50)
UC_ShipType("Dreadnaught", 1)
UC_ShipType("Battlecruiser", 3)
UC_ShipType("ResourceCollector", 20)
UC_ShipType("ResourceController", 4)
UC_ShipType("Probe", 10)
UC_ShipType("ECMProbe", 10)
UC_ShipType("ProximitySensor", 10)
UC_Family("Platform", 20)
UC_ShipType("HyperspacePlatform", 4)
UC_Family("Mothership", 6)
UC_Family("SinglePlayerMisc", 100)
