-- LuaDC version 0.9.19
-- 5/23/2004 7:23:49 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
UC_Family("Fighter", 7)
UC_FamilyOverride("Vaygr", "Fighter", 8)
UC_Family("Corvette", 6)
UC_ShipType("MinelayerCorvette", 3)
UC_Family("Frigate", 11)
UC_ShipType("DefenseFieldFrigate", 1)
UC_ShipType("CaptureFrigate", 3)
UC_ShipTypeOverride("Hiigaran", "CaptureFrigate", 2)
UC_Family("Capital", 7)
UC_FamilyOverride("Vaygr", "Capital", 8)
UC_ShipType("Destroyer", 3)
UC_ShipType("Carrier", 2)
UC_ShipTypeOverride("Vaygr", "Carrier", 3)
UC_ShipType("Battlecruiser", 2)
UC_ShipType("Shipyard", 1)
UC_Family("Utility", 50)
UC_ShipType("Dreadnaught", 1)
UC_ShipType("Battlecruiser", 2)
UC_ShipType("ResourceCollector", 20)
UC_ShipType("ResourceController", 4)
UC_ShipType("Probe", 10)
UC_ShipType("ECMProbe", 10)
UC_ShipType("ProximitySensor", 10)
UC_Family("Platform", 20)
UC_ShipType("HyperspacePlatform", 4)
UC_Family("Mothership", 6)
UC_Family("SinglePlayerMisc", 100)